helper = require('atom-syntax-tools')
path = require('path');

# Start out by re-exporting our helper's stuff.   This helps encapsulate things.
module.exports = exports = Object.assign(helper)

#exports.makeGrammar = makeGrammar = (args...) -> helper.makeGrammar args...
exports.writeGrammar = writeGrammar = (grammar, how ='CSON' ) -> helper.makeGrammar grammar, how
exports.genericGrammarComment = genericGrammarComment = (p = __filename ) ->
  basename = path.basename(p)
  [
    "# ----------------------------------------------------------------------"
    "# ATTENTION!  If you are reading this from :"
    "#"
    "#    (a) the original CoffeeScript source (#{basename})"
    "#"
    "#     => OK, you are in the RIGHT place. Just SKIP this comment."
    "#"
    "#    (b) any other place, such as: "
    "#          - an atom grammar definition file in CSON"
    "#          - or a dump of some sorts (that spewed oout the generated atom grammar object)"
    "#"
    "#     => STOP! You are in te WRONG place (which is an autogenerated ugly file)."
    "#        Just read the rest this comment and then go find the original"
    "#        CoffeScript source mentioned above."
    "#        It is much more pleasent to look at, I assure you. :-)"
    "#"
    "# PS: I hope you were not really thinking I was clever and crazy enough to write"
    "# that damned regex in one huge line without free-spacing :)"
    "# ----------------------------------------------------------------------"
  ]
